In [90]:
import pandas as pd
import numpy as np

In [91]:
pd.__version__

'1.0.1'

In [92]:
covid19 = pd.read_csv("Anaconda/RKI_COVID19.csv")

In [93]:
covid19.head()

,FID,IdBundesland,Bundesland,Landkreis,Altersgruppe,Geschlecht,AnzahlFall,AnzahlTodesfall,Meldedatum,IdLandkreis,Datenstand,NeuerFall,NeuerTodesfall,Refdatum,NeuGenesen,AnzahlGenesen,IstErkrankungsbeginn,Altersgruppe2
0,10110919,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/14 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/16 00:00:00,0,1,1,Nicht übermittelt
1,10110920,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/19 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/13 00:00:00,0,1,1,Nicht übermittelt
2,10110921,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/19 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/16 00:00:00,0,1,1,Nicht übermittelt
3,10110922,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/21 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/13 00:00:00,0,1,1,Nicht übermittelt
4,10110923,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/27 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/22 00:00:00,0,1,1,Nicht übermittelt

In [94]:
type(covid19)

pandas.core.frame.DataFrame

In [95]:
covid19.columns

Index(['FID', 'IdBundesland', 'Bundesland', 'Landkreis', 'Altersgruppe',
       'Geschlecht', 'AnzahlFall', 'AnzahlTodesfall', 'Meldedatum',
       'IdLandkreis', 'Datenstand', 'NeuerFall', 'NeuerTodesfall', 'Refdatum',
       'NeuGenesen', 'AnzahlGenesen', 'IstErkrankungsbeginn', 'Altersgruppe2'],
      dtype='object')

In [96]:
covid19[covid19['Landkreis'].str.contains('ü')]

,FID,IdBundesland,Bundesland,Landkreis,Altersgruppe,Geschlecht,AnzahlFall,AnzahlTodesfall,Meldedatum,IdLandkreis,Datenstand,NeuerFall,NeuerTodesfall,Refdatum,NeuGenesen,AnzahlGenesen,IstErkrankungsbeginn,Altersgruppe2
305,10111224,1,Schleswig-Holstein,SK Lübeck,A00-A04,M,1,0,2020/03/23 00:00:00,1003,"03.06.2020, 00:00 Uhr",0,-9,2020/03/21 00:00:00,0,1,1,Nicht übermittelt
306,10111225,1,Schleswig-Holstein,SK Lübeck,A00-A04,M,1,0,2020/04/01 00:00:00,1003,"03.06.2020, 00:00 Uhr",0,-9,2020/03/26 00:00:00,0,1,1,Nicht übermittelt
307,10111226,1,Schleswig-Holstein,SK Lübeck,A00-A04,M,1,0,2020/04/13 00:00:00,1003,"03.06.2020, 00:00 Uhr",0,-9,2020/04/09 00:00:00,0,1,1,Nicht übermittelt
308,10111227,1,Schleswig-Holstein,SK Lübeck,A00-A04,M,1,0,2020/04/17 00:00:00,1003,"03.06.2020, 00:00 Uhr",0,-9,2020/04/17 00:00:00,0,1,0,Nicht übermittelt
309,10111228,1,Schleswig-Holstein,SK Lübeck,A00-A04,M,1,0,2020/04/30 00:00:00,1003,"03.06.2020, 00:00 Uhr",0,-9,2020/04/23 00:00:00,0,1,1,Nicht übermittelt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142773,10253692,15,Sachsen-Anhalt,LK Mansfeld-Südharz,A60-A79,W,1,0,2020/05/21 00:00:00,15087,"03.06.2020, 00:00 Uhr",0,-9,2020/05/21 00:00:00,-9,0,0,Nicht übermittelt
142774,10253693,15,Sachsen-Anhalt,LK Mansfeld-Südharz,A80+,M,1,1,2020/04/20 00:00:00,15087,"03.06.2020, 00:00 Uhr",0,0,2020/04/17 00:00:00,-9,0,1,Nicht übermittelt
142775,10253694,15,Sachsen-Anhalt,LK Mansfeld-Südharz,A80+,W,1,0,2020/04/03 00:00:00,15087,"03.06.2020, 00:00 Uhr",0,-9,2020/03/28 00:00:00,0,1,1,Nicht übermittelt
142776,10253695,15,Sachsen-Anhalt,LK Mansfeld-Südharz,A80+,W,1,0,2020/05/10 00:00:00,15087,"03.06.2020, 00:00 Uhr",0,-9,2020/05/08 00:00:00,-9,0,1,Nicht übermittelt
142777,10253696,15,Sachsen-Anhalt,LK Mansfeld-Südharz,A80+,W,1,0,2020/05/21 00:00:00,15087,"03.06.2020, 00:00 Uhr",0,-9,2020/05/21 00:00:00,-9,0,0,Nicht übermittelt

In [97]:
einwohner = pd.read_csv("Anaconda/12411_0016_edited.csv", encoding='utf8', delimiter=";")
einwohner[einwohner[['Insgesamt']] == 'NaN'] = np.nan

In [98]:
einwohner

,Stichtag,ID,Kreise,männlich,weiblich,Insgesamt
0,31.12.2018,1001.0,"Flensburg, kreisfreie Stadt",44599,44905,89504
1,31.12.2018,1002.0,"Kiel, kreisfreie Stadt",120566,126982,247548
2,31.12.2018,1003.0,"Lübeck, kreisfreie Stadt",104371,112827,217198
3,31.12.2018,1004.0,"Neumünster, kreisfreie Stadt",39241,40246,79487
4,31.12.2018,1051.0,"Dithmarschen, Landkreis",65720,67490,133210
...,...,...,...,...,...,...
475,31.12.2018,16077.0,"Altenburger Land, Landkreis",44138,45980,90118
476,__________,NaN,NaN,NaN,NaN,NaN
477,Ab 2011: Ergebnisse auf Grundlage des Zensus 2...,NaN,NaN,NaN,NaN,NaN
478,"© Statistisches Bundesamt (Destatis), 2020",NaN,NaN,NaN,NaN,NaN
479,Stand: 02.06.2020 / 12:33:16,NaN,NaN,NaN,NaN,NaN

In [99]:
covid19.groupby(['IdLandkreis', 'Landkreis', 'IdBundesland']).sum()

,,,FID,AnzahlFall,AnzahlTodesfall,NeuerFall,NeuerTodesfall,NeuGenesen,AnzahlGenesen,IstErkrankungsbeginn
IdLandkreis,Landkreis,IdBundesland,,,,,,,,
1001,SK Flensburg,1,414548499,42,3,0,-342,-90,31,34
1002,SK Kiel,1,2669328156,279,9,0,-2295,-89,269,221
1003,SK Lübeck,1,1577363034,169,1,2,-1395,-17,167,138
1004,SK Neumünster,1,758356275,79,2,0,-657,-27,76,65
1051,LK Dithmarschen,1,566243020,59,3,0,-477,-27,56,51
...,...,...,...,...,...,...,...,...,...,...
16073,LK Saalfeld-Rudolstadt,16,697412998,71,0,0,-612,-36,66,55
16074,LK Saale-Holzland-Kreis,16,646136757,71,3,0,-540,-63,64,37
16075,LK Saale-Orla-Kreis,16,1394848436,148,12,1,-1134,-153,131,116
16076,LK Greiz,16,5753945307,625,45,0,-4653,-768,535,490
16077,LK Altenburger Land,16,707726238,71,3,0,-594,-81,61,61

In [100]:
einwohner

,Stichtag,ID,Kreise,männlich,weiblich,Insgesamt
0,31.12.2018,1001.0,"Flensburg, kreisfreie Stadt",44599,44905,89504
1,31.12.2018,1002.0,"Kiel, kreisfreie Stadt",120566,126982,247548
2,31.12.2018,1003.0,"Lübeck, kreisfreie Stadt",104371,112827,217198
3,31.12.2018,1004.0,"Neumünster, kreisfreie Stadt",39241,40246,79487
4,31.12.2018,1051.0,"Dithmarschen, Landkreis",65720,67490,133210
...,...,...,...,...,...,...
475,31.12.2018,16077.0,"Altenburger Land, Landkreis",44138,45980,90118
476,__________,NaN,NaN,NaN,NaN,NaN
477,Ab 2011: Ergebnisse auf Grundlage des Zensus 2...,NaN,NaN,NaN,NaN,NaN
478,"© Statistisches Bundesamt (Destatis), 2020",NaN,NaN,NaN,NaN,NaN
479,Stand: 02.06.2020 / 12:33:16,NaN,NaN,NaN,NaN,NaN

In [101]:
einwohner.loc[einwohner['ID'] == 1001]

     Stichtag      ID                       Kreise männlich weiblich Insgesamt
0  31.12.2018  1001.0  Flensburg, kreisfreie Stadt    44599    44905     89504

In [102]:
covid19.loc[covid19['IdLandkreis'] == 1001]

,FID,IdBundesland,Bundesland,Landkreis,Altersgruppe,Geschlecht,AnzahlFall,AnzahlTodesfall,Meldedatum,IdLandkreis,Datenstand,NeuerFall,NeuerTodesfall,Refdatum,NeuGenesen,AnzahlGenesen,IstErkrankungsbeginn,Altersgruppe2
0,10110919,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/14 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/16 00:00:00,0,1,1,Nicht übermittelt
1,10110920,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/19 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/13 00:00:00,0,1,1,Nicht übermittelt
2,10110921,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/19 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/16 00:00:00,0,1,1,Nicht übermittelt
3,10110922,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/21 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/13 00:00:00,0,1,1,Nicht übermittelt
4,10110923,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/27 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/22 00:00:00,0,1,1,Nicht übermittelt
5,10110924,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/04/04 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/04/01 00:00:00,0,1,1,Nicht übermittelt
6,10110925,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/04/06 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/04/02 00:00:00,0,1,1,Nicht übermittelt
7,10110926,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/04/07 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/04/02 00:00:00,0,1,1,Nicht übermittelt
8,10110927,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/04/09 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/04/05 00:00:00,0,1,1,Nicht übermittelt
9,10110928,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/05/29 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/05/29 00:00:00,-9,0,0,Nicht übermittelt
10,10110929,1,Schleswig-Holstein,SK Flensburg,A15-A34,W,1,0,2020/03/14 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/12 00:00:00,0,1,1,Nicht übermittelt
11,10110930,1,Schleswig-Holstein,SK Flensburg,A15-A34,W,1,0,2020/03/18 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/11 00:00:00,0,1,1,Nicht übermittelt
12,10110931,1,Schleswig-Holstein,SK Flensburg,A15-A34,W,1,0,2020/03/18 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/15 00:00:00,0,1,1,Nicht übermittelt
13,10110932,1,Schleswig-Holstein,SK Flensburg,A15-A34,W,1,0,2020/03/28 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/14 00:00:00,0,1,1,Nicht übermittelt
14,10110933,1,Schleswig-Holstein,SK Flensburg,A15-A34,W,1,0,2020/05/21 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/05/21 00:00:00,-9,0,0,Nicht übermittelt
15,10110934,1,Schleswig-Holstein,SK Flensburg,A35-A59,M,1,0,2020/03/14 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/16 00:00:00,0,1,1,Nicht übermittelt
16,10110935,1,Schleswig-Holstein,SK Flensburg,A35-A59,M,1,0,2020/03/20 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/17 00:00:00,0,1,1,Nicht übermittelt
17,10110936,1,Schleswig-Holstein,SK Flensburg,A35-A59,M,1,0,2020/05/05 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/04/30 00:00:00,0,1,1,Nicht übermittelt
18,10110937,1,Schleswig-Holstein,SK Flensburg,A35-A59,M,1,0,2020/05/21 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/05/21 00:00:00,-9,0,0,Nicht übermittelt
19,10110938,1,Schleswig-Holstein,SK Flensburg,A35-A59,W,1,0,2020/03/14 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/10 00:00:00,0,1,1,Nicht übermittelt
20,10110939,1,Schleswig-Holstein,SK Flensburg,A35-A59,W,1,0,2020/03/19 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/17 00:00:00,0,1,1,Nicht übermittelt
21,10110940,1,Schleswig-Holstein,SK Flensburg,A35-A59,W,1,0,2020/03/19 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/20 00:00:00,0,1,1,Nicht übermittelt
22,10110941,1,Schleswig-Holstein,SK Flensburg,A35-A59,W,1,0,2020/03/20 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/17 00:00:00,0,1,1,Nicht übermittelt
23,10110942,1,Schleswig-Holstein,SK Flensburg,A35-A59,W,1,0,2020/03/28 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/14 00:00:00,0,1,1,Nicht übermittelt
24,10110943,1,Schleswig-Holstein,SK Flensburg,A35-A59,W,1,0,2020/03/29 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/19 00:00:00,0,1,1,Nicht übermittelt
25,10110944,1,Schleswig-Holstein,SK Flensburg,A35-A59,W,1,0,2020/04/03 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/31 00:00:00,0,1,1,Nicht übermittelt
26,10110945,1,Schleswig-Holstein,SK Flensburg,A35-A59,W,1,0,2020/05/17 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/05/17 00:00:00,0,1,0,Nicht übermittelt
27,10110946,1,Schleswig-Holstein,SK Flensburg,A35-A59,W,2,0,2020/05/21 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/05/21 00:00:00,-9,0,0,Nicht übermittelt
28,10110947,1,Schleswig-Holstein,SK Flensburg,A35-A59,W,1,0,2020/05/22 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/05/22 00:00:00,-9,0,0,Nicht übermittelt
29,10110948,1,Schleswig-Holstein,SK Flensburg,A35-A59,W,1,0,2020/05/30 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/05/28 00:00:00,-9,0,1,Nicht übermittelt
30,10110949,1,Schleswig-Holstein,SK Flensburg,A60-A79,M,1,1,2020/03/24 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,0,2020/03/19 00:00:00,-9,0,1,Nicht übermittelt
31,10110950,1,Schleswig-Holstein,SK Flensburg,A60-A79,M,1,0,2020/03/26 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/19 00:00:00,0,1,1,Nicht übermittelt
32,10110951,1,Schleswig-Holstein,SK Flensburg,A60-A79,M,1,0,2020/03/26 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/22 00:00:00,0,1,1,Nicht übermittelt
33,10110952,1,Schleswig-Holstein,SK Flensburg,A60-A79,M,1,1,2020/04/10 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,0,2020/04/04 00:00:00,-9,0,1,Nicht übermittelt
34,10110953,1,Schleswig-Holstein,SK Flensburg,A60-A79,M,1,0,2020/05/26 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/05/26 00:00:00,-9,0,0,Nicht übermittelt
35,10110954,1,Schleswig-Holstein,SK Flensburg,A60-A79,W,1,0,2020/03/26 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/22 00:00:00,0,1,1,Nicht übermittelt
36,10110955,1,Schleswig-Holstein,SK Flensburg,A60-A79,W,1,0,2020/03/26 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/26 00:00:00,0,1,1,Nicht übermittelt
37,10110956,1,Schleswig-Holstein,SK Flensburg,A60-A79,W,1,0,2020/04/03 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/21 00:00:00,0,1,1,Nicht übermittelt
38,10110957,1,Schleswig-Holstein,SK Flensburg,A80+,M,1,0,2020/03/31 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/20 00:00:00,0,1,1,Nicht übermittelt
39,10110958,1,Schleswig-Holstein,SK Flensburg,A80+,M,1,1,2020/03/31 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,0,2020/03/21 00:00:00,-9,0,1,Nicht übermittelt
40,10110959,1,Schleswig-Holstein,SK Flensburg,A80+,W,1,0,2020/03/30 00:00:00,1001,"03.06.2020, 00:00 Uhr",0,-9,2020/03/26 00:00:00,0,1,1,Nicht übermittelt

In [103]:
mergeSet = pd.merge(covid19.groupby(['IdLandkreis', 'Landkreis']).sum(), einwohner, left_on = 'IdLandkreis', right_on = 'ID')

In [104]:
mergeSet

,FID,IdBundesland,AnzahlFall,AnzahlTodesfall,NeuerFall,NeuerTodesfall,NeuGenesen,AnzahlGenesen,IstErkrankungsbeginn,Stichtag,ID,Kreise,männlich,weiblich,Insgesamt
0,414548499,41,42,3,0,-342,-90,31,34,31.12.2018,1001.0,"Flensburg, kreisfreie Stadt",44599,44905,89504
1,2669328156,264,279,9,0,-2295,-89,269,221,31.12.2018,1002.0,"Kiel, kreisfreie Stadt",120566,126982,247548
2,1577363034,156,169,1,2,-1395,-17,167,138,31.12.2018,1003.0,"Lübeck, kreisfreie Stadt",104371,112827,217198
3,758356275,75,79,2,0,-657,-27,76,65,31.12.2018,1004.0,"Neumünster, kreisfreie Stadt",39241,40246,79487
4,566243020,56,59,3,0,-477,-27,56,51,31.12.2018,1051.0,"Dithmarschen, Landkreis",65720,67490,133210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,697412998,1088,71,0,0,-612,-36,66,55,31.12.2018,16073.0,"Saalfeld-Rudolstadt, Landkreis",52388,53968,106356
396,646136757,1008,71,3,0,-540,-63,64,37,31.12.2018,16074.0,Saale-Holzland-Kreis,41360,41691,83051
397,1394848436,2176,148,12,1,-1134,-153,131,116,31.12.2018,16075.0,Saale-Orla-Kreis,40119,40749,80868
398,5753945307,8976,625,45,0,-4653,-768,535,490,31.12.2018,16076.0,"Greiz, Landkreis",48326,49833,98159
399,707726238,1104,71,3,0,-594,-81,61,61,31.12.2018,16077.0,"Altenburger Land, Landkreis",44138,45980,90118

In [105]:
corMatrix = mergeSet[['Kreise', 'Insgesamt']]

In [106]:
print(corMatrix.corr())

Empty DataFrame
Columns: []
Index: []

In [107]:
mergeSet[['Kreise', 'Insgesamt', 'AnzahlFall']]

                             Kreise Insgesamt  AnzahlFall
0       Flensburg, kreisfreie Stadt     89504          42
1            Kiel, kreisfreie Stadt    247548         279
2          Lübeck, kreisfreie Stadt    217198         169
3      Neumünster, kreisfreie Stadt     79487          79
4           Dithmarschen, Landkreis    133210          59
..                              ...       ...         ...
395  Saalfeld-Rudolstadt, Landkreis    106356          71
396            Saale-Holzland-Kreis     83051          71
397                Saale-Orla-Kreis     80868         148
398                Greiz, Landkreis     98159         625
399     Altenburger Land, Landkreis     90118          71

[400 rows x 3 columns]

In [108]:
mergeSet

,FID,IdBundesland,AnzahlFall,AnzahlTodesfall,NeuerFall,NeuerTodesfall,NeuGenesen,AnzahlGenesen,IstErkrankungsbeginn,Stichtag,ID,Kreise,männlich,weiblich,Insgesamt
0,414548499,41,42,3,0,-342,-90,31,34,31.12.2018,1001.0,"Flensburg, kreisfreie Stadt",44599,44905,89504
1,2669328156,264,279,9,0,-2295,-89,269,221,31.12.2018,1002.0,"Kiel, kreisfreie Stadt",120566,126982,247548
2,1577363034,156,169,1,2,-1395,-17,167,138,31.12.2018,1003.0,"Lübeck, kreisfreie Stadt",104371,112827,217198
3,758356275,75,79,2,0,-657,-27,76,65,31.12.2018,1004.0,"Neumünster, kreisfreie Stadt",39241,40246,79487
4,566243020,56,59,3,0,-477,-27,56,51,31.12.2018,1051.0,"Dithmarschen, Landkreis",65720,67490,133210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,697412998,1088,71,0,0,-612,-36,66,55,31.12.2018,16073.0,"Saalfeld-Rudolstadt, Landkreis",52388,53968,106356
396,646136757,1008,71,3,0,-540,-63,64,37,31.12.2018,16074.0,Saale-Holzland-Kreis,41360,41691,83051
397,1394848436,2176,148,12,1,-1134,-153,131,116,31.12.2018,16075.0,Saale-Orla-Kreis,40119,40749,80868
398,5753945307,8976,625,45,0,-4653,-768,535,490,31.12.2018,16076.0,"Greiz, Landkreis",48326,49833,98159
399,707726238,1104,71,3,0,-594,-81,61,61,31.12.2018,16077.0,"Altenburger Land, Landkreis",44138,45980,90118

In [109]:
mergeSet[['AnzahlFall']].corr()

            AnzahlFall
AnzahlFall         1.0

In [110]:
einwohner.corr()

     ID
ID  1.0

In [111]:
einwohner

,Stichtag,ID,Kreise,männlich,weiblich,Insgesamt
0,31.12.2018,1001.0,"Flensburg, kreisfreie Stadt",44599,44905,89504
1,31.12.2018,1002.0,"Kiel, kreisfreie Stadt",120566,126982,247548
2,31.12.2018,1003.0,"Lübeck, kreisfreie Stadt",104371,112827,217198
3,31.12.2018,1004.0,"Neumünster, kreisfreie Stadt",39241,40246,79487
4,31.12.2018,1051.0,"Dithmarschen, Landkreis",65720,67490,133210
...,...,...,...,...,...,...
475,31.12.2018,16077.0,"Altenburger Land, Landkreis",44138,45980,90118
476,__________,NaN,NaN,NaN,NaN,NaN
477,Ab 2011: Ergebnisse auf Grundlage des Zensus 2...,NaN,NaN,NaN,NaN,NaN
478,"© Statistisches Bundesamt (Destatis), 2020",NaN,NaN,NaN,NaN,NaN
479,Stand: 02.06.2020 / 12:33:16,NaN,NaN,NaN,NaN,NaN

In [112]:
test = np.nan

In [113]:
test

nan

In [114]:
mergeSet

,FID,IdBundesland,AnzahlFall,AnzahlTodesfall,NeuerFall,NeuerTodesfall,NeuGenesen,AnzahlGenesen,IstErkrankungsbeginn,Stichtag,ID,Kreise,männlich,weiblich,Insgesamt
0,414548499,41,42,3,0,-342,-90,31,34,31.12.2018,1001.0,"Flensburg, kreisfreie Stadt",44599,44905,89504
1,2669328156,264,279,9,0,-2295,-89,269,221,31.12.2018,1002.0,"Kiel, kreisfreie Stadt",120566,126982,247548
2,1577363034,156,169,1,2,-1395,-17,167,138,31.12.2018,1003.0,"Lübeck, kreisfreie Stadt",104371,112827,217198
3,758356275,75,79,2,0,-657,-27,76,65,31.12.2018,1004.0,"Neumünster, kreisfreie Stadt",39241,40246,79487
4,566243020,56,59,3,0,-477,-27,56,51,31.12.2018,1051.0,"Dithmarschen, Landkreis",65720,67490,133210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,697412998,1088,71,0,0,-612,-36,66,55,31.12.2018,16073.0,"Saalfeld-Rudolstadt, Landkreis",52388,53968,106356
396,646136757,1008,71,3,0,-540,-63,64,37,31.12.2018,16074.0,Saale-Holzland-Kreis,41360,41691,83051
397,1394848436,2176,148,12,1,-1134,-153,131,116,31.12.2018,16075.0,Saale-Orla-Kreis,40119,40749,80868
398,5753945307,8976,625,45,0,-4653,-768,535,490,31.12.2018,16076.0,"Greiz, Landkreis",48326,49833,98159
399,707726238,1104,71,3,0,-594,-81,61,61,31.12.2018,16077.0,"Altenburger Land, Landkreis",44138,45980,90118

In [124]:
einwohner.loc[einwohner['ID'] == 3152]

,Stichtag,ID,Kreise,männlich,weiblich,Insgesamt
20,31.12.2018,3152.0,"Göttingen, Landkreis (bis 31.10.2016)",-,-,-

In [136]:
einwohner[['Insgesamt']]

    Insgesamt
0       89504
1      247548
2      217198
3       79487
4      133210
..        ...
475     90118
476       NaN
477       NaN
478       NaN
479       NaN

[480 rows x 1 columns]

In [139]:
mergeSet['testSpalte'] = mergeSet['ID'] / 10

In [140]:
mergeSet

,FID,IdBundesland,AnzahlFall,AnzahlTodesfall,NeuerFall,NeuerTodesfall,NeuGenesen,AnzahlGenesen,IstErkrankungsbeginn,Stichtag,ID,Kreise,männlich,weiblich,Insgesamt,testSpalte
0,414548499,41,42,3,0,-342,-90,31,34,31.12.2018,1001.0,"Flensburg, kreisfreie Stadt",44599,44905,89504,100.1
1,2669328156,264,279,9,0,-2295,-89,269,221,31.12.2018,1002.0,"Kiel, kreisfreie Stadt",120566,126982,247548,100.2
2,1577363034,156,169,1,2,-1395,-17,167,138,31.12.2018,1003.0,"Lübeck, kreisfreie Stadt",104371,112827,217198,100.3
3,758356275,75,79,2,0,-657,-27,76,65,31.12.2018,1004.0,"Neumünster, kreisfreie Stadt",39241,40246,79487,100.4
4,566243020,56,59,3,0,-477,-27,56,51,31.12.2018,1051.0,"Dithmarschen, Landkreis",65720,67490,133210,105.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,697412998,1088,71,0,0,-612,-36,66,55,31.12.2018,16073.0,"Saalfeld-Rudolstadt, Landkreis",52388,53968,106356,1607.3
396,646136757,1008,71,3,0,-540,-63,64,37,31.12.2018,16074.0,Saale-Holzland-Kreis,41360,41691,83051,1607.4
397,1394848436,2176,148,12,1,-1134,-153,131,116,31.12.2018,16075.0,Saale-Orla-Kreis,40119,40749,80868,1607.5
398,5753945307,8976,625,45,0,-4653,-768,535,490,31.12.2018,16076.0,"Greiz, Landkreis",48326,49833,98159,1607.6
399,707726238,1104,71,3,0,-594,-81,61,61,31.12.2018,16077.0,"Altenburger Land, Landkreis",44138,45980,90118,1607.7